language: android
android:
  components:
  - build-tools-$BUILD_TOOL
  - android-$ANDROID_API
  - extra-android-m2repository
install:
  - rvm install 2.3.4
  - gem install fastlane
after_success:
  - "./ci/deploy.sh"
notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
env:
  global:
  - BUILD_TOOL=22.0.1
  - ANDROID_API=26
before_install:
  - openssl aes-256-cbc -K $encrypted_fbe35f3d891b_key -iv $encrypted_fbe35f3d891b_iv
    -in google.tar.gz.enc -out ci/google.tar.gz -d