title: android inventory agent
baseurl: "/android-inventory-agent"
url: "http://glpi-project.github.io"
image: http://glpi-project.github.io/android-inventory-agent/images/logo2.png
email: sales@teclib.com
twitter: https://twitter.com/glpi_project
facebook: https://www.facebook.com/glpiproject/
telegram: https://t.me/glpien
irc: http://webchat.freenode.net/?channels=glpi
reddit: https://www.reddit.com/r/glpi/

# Build settings
markdown: kramdown

sass:
  style: compressed

plugins:
  - jekyll-github-metadata
  - jekyll-feed
  - jekyll-sitemap

repository: flyve-mdm/android-inventory-agent

prose:

  rooturl: '_posts' 
  
  ignore:
    - .keep

  media: "images"

  metadata:
    _posts:
      - name: "category"
        field:
          element: "hidden"
          value: "blog"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "published"
        field:
          element: "checkbox"
          label: "Published"
          value: false
      - name: "hackerNewsURL"
        field:
          element: "text"
          label: Hacker News URL
          value: ""
      - name: "redditURL"
        field:
          element: "text" 
          label: Reddit URL
          value: ""
    
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
      - name: "howtos"
        field:
          element: "checkbox"
          label: "howtos"
          value: false
      - name: "published"
        field:
          element: "checkbox"
          label: "Published"
          value: false
      - name: "description"
        field:
          element: "textarea"
          label: "Description"
      - name: "hackerNewsURL"
        field:
          element: "text"
          label: Hacker News URL
          value: ""
      - name: "redditURL"
        field:
          element: "text" 
          label: Reddit URL
          value: ""

