version: 2
jobs:
  flyve_build:
    working_directory: ~/flyve
    docker:
      # Android the primary container
      - image: circleci/android:api-26-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
  flyve_test:
    working_directory: ~/flyve
    docker:
        - image: circleci/android:api-26-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
  flyve_deploy:
    working_directory: ~/flyve
    docker:
      # Android the primary container
      - image: circleci/android:api-26-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Setup environment
          command: source ci/scripts/ci_setup.sh
      - run:
          name: Update version and code
          command: source ci/scripts/ci_updateversion.sh
      - run:
          name: Create apk
          command: ./gradlew assemble
      - run:
          name: Deploy to Google Play
          command: source ci/scripts/ci_google_play.sh "beta"
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

workflows:
  version: 2
  build_and_test:
    jobs:
      - flyve_deploy
#      - flyve_build
#      - flyve_test:
#          requires:
#            - flyve_build
#      - flyve_deploy:
#          requires:
#            - flyve_test
