version: 2
jobs:
  flyve_build:
    working_directory: ~/code
    docker:
      # Android the primary container
      - image: circleci/android:api-23-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
  flyve_test:
    working_directory: ~/code
    docker:
        - image: circleci/android:api-23-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
  flyve_deploy:
    working_directory: ~/code
    docker:
      # Android the primary container
      - image: circleci/android:api-23-alpha
      - image: circleci/ruby:2.4.1-node
      - image: circleci/python:3.6.2
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Setup environment
          command: ci/scripts/ci_setup.sh
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

workflows:
  version: 2
  build_and_test:
    jobs:
      - flyve_deploy
#      - flyve_build
#      - flyve_test:
#          requires:
#            - flyve_build
#      - flyve_deploy:
#          requires:
#            - flyve_test
